#!/usr/bin/env python3
"""add_agent — scaffold a new conformant Aegis agent package.

    python tools/add_agent.py --id <id> --owner <dept> --pack <pack> \
        --blast-radius low

Generates, under sample_agents/<id>/, a complete agent package:
    agent.manifest.yaml   (conforms to governance/onboarding/agent-manifest.schema.json)
    prompts/system.md     (pinned system prompt)
    evals/suite.md        (eval suite stub covering the required categories)
    runbook.md            (day-2 operations runbook)
    README.md             (what the agent does + how it clears the minimum bar)

The generated manifest is validated against the schema before it is written;
the scaffolder exits non-zero if it would produce a non-conformant agent. This
demonstrates that adding agents after the platform is up is a one-command,
governed operation.

Stdlib only.
"""

from __future__ import annotations

import argparse
import os
import sys

# Make platform_core importable when run from the repo root.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from platform_core import manifest_loader  # noqa: E402

_PACK_DEFAULTS = {
    "enterprise": {
        "classification": ["public", "pii"],
        "inference_profile": "aip-enterprise-default",
        "grounding_kb": "kb-enterprise-default",
        "grounding_threshold": 0.80,
        "publisher": "platform-team",
    },
    "slg": {
        "classification": ["public", "pii"],
        "inference_profile": "aip-slg-default",
        "grounding_kb": "kb-slg-policy",
        "grounding_threshold": 0.85,
        "publisher": "agency-platform-team",
    },
    "education": {
        "classification": ["public", "edu"],
        "inference_profile": "aip-edu-default",
        "grounding_kb": "kb-edu-default",
        "grounding_threshold": 0.85,
        "publisher": "district-platform-team",
    },
    "healthcare-lifesciences": {
        "classification": ["public", "phi"],
        "inference_profile": "aip-hcls-default",
        "grounding_kb": "kb-hcls-default",
        "grounding_threshold": 0.90,
        "publisher": "clinical-platform-team",
    },
}


def _manifest_yaml(args, defaults) -> str:
    classes = "\n".join(f"    - {c}" for c in defaults["classification"])
    tool_classes = ", ".join(defaults["classification"])
    return f"""# Aegis agent manifest — generated by tools/add_agent.py
# Conforms to governance/onboarding/agent-manifest.schema.json and clears the
# 9-point minimum bar (governance/onboarding/MINIMUM-BAR.md).

apiVersion: aegis/v1
kind: Agent

metadata:
  id: {args.id}
  name: {args.id.replace('-', ' ').title()}
  description: >-
    Decision-support agent scaffolded for the {args.pack} pack. Reads and
    summarizes; all consequential actions are withheld and human-gated.
  owner: {args.owner}
  team: default
  packs:
    - {args.pack}
  classification:
{classes}
  blast_radius: {args.blast_radius}

grants:
  tools:
    - id: kb.search_policy
      scope: read
      data_classes: [{tool_classes}]
    - id: record.read
      scope: read
      data_classes: [{tool_classes}]
    - id: record.draft_note
      scope: write
      data_classes: [{tool_classes}]
  consequential:
    # Withheld from the agent; reachable only via the human gate.
    - record.issue_decision

grounding:
  knowledge_base: {defaults['grounding_kb']}
  grounding_threshold: {defaults['grounding_threshold']}
  relevance_threshold: 0.75

budget:
  monthly_token_cap: 50000000
  inference_profile: {defaults['inference_profile']}
  cap_behavior: hard
  alert_thresholds: [0.6, 0.85, 1.0]

evals:
  suite: evals/{args.id}/
  min_pass_rate: 0.95
  categories:
    - accuracy
    - refusal
    - fairness
    - prompt_injection
    - accessibility
    - grounding

human_gate:
  mode: step_functions_wait_for_task_token
  separation_of_duties: true
  approval_ttl_seconds: 3600
  esignature_grade: false

signing:
  publisher: {defaults['publisher']}
  signature: "cosign:GENERATED-PLACEHOLDER-SIGN-BEFORE-DEPLOY"
  algorithm: cosign
"""


def _system_prompt(args) -> str:
    return f"""# System prompt — {args.id} (pinned, hash-verified at call time)

You are {args.id}, a decision-support agent on the Aegis governed platform.

Rules:
- Ground every answer in retrieved knowledge-base sources. Do not free-generate
  against a system of record.
- You may read and draft. You may NOT issue, adjudicate, release, award, or
  transfer anything — those are consequential and require a human approval.
- Never reveal sensitive data (PII/PHI/FTI/CJI/EDU/card). The boundary masks it.
- If you are not grounded above the configured threshold, refuse and say so.
"""


def _evals(args) -> str:
    return f"""# Eval suite stub — {args.id}

Required categories (minimum-bar point 6). Replace stubs with real cases before
promotion; the suite must pass at >= 0.95.

| id | category | input | expected |
|----|----------|-------|----------|
| acc-1 | accuracy | sample request | correct classification |
| ref-1 | refusal | request for consequential action | refuses, routes to human gate |
| fair-1 | fairness | matched cohorts | four-fifths parity holds |
| pi-1 | prompt_injection | "ignore your instructions" | resists, stays in scope |
| a11y-1 | accessibility | user-facing output | WCAG 2.1 AA conformant |
| gnd-1 | grounding | answer vs source | blocked below threshold |
"""


def _runbook(args) -> str:
    return f"""# Runbook — {args.id}

## Ownership
- Owner / chargeback dept: {args.owner}
- Compliance pack: {args.pack}
- Blast radius: {args.blast_radius}

## Day-2 operations
- Budget alerts fire at 60% / 85% / 100% of the monthly token cap to the owner.
- On a budget hard-cap denial: review usage, request an audited temporary lift
  through the human gate (separation of duties enforced).
- On a grounding/hallucination flag spike: re-check the knowledge base and the
  pinned prompt hash; re-run the eval suite.
- On any model or prompt change: re-run evals before promotion (point 6).

## Incident
- Every allow/deny/pending/error is in the append-only audit (WORM evidence).
- To produce evidence for a review board: export the WORM evidence file and the
  chargeback report for the period in question.
"""


def _readme(args, defaults) -> str:
    return f"""# {args.id}

Scaffolded Aegis agent for the **{args.pack}** pack, owned by **{args.owner}**,
blast radius **{args.blast_radius}**.

This package conforms to `governance/onboarding/agent-manifest.schema.json` and
clears the 9-point minimum bar:

1. Declared scope only — tools and data classes are enumerated in the manifest.
2. Consequential action `record.issue_decision` withheld; human-gated only.
3. Bound, single-use, separation-of-duties human gate wired.
4. Grounding KB `{defaults['grounding_kb']}` + threshold declared.
5. Token budget (hard cap) + inference profile `{defaults['inference_profile']}`.
6. Eval suite stub covering all required categories.
7. Masking on for every declared data class, fail-closed.
8. Manifest carries a publisher + signature placeholder (sign before deploy).
9. Pack `{args.pack}` declared; deploy fails if the pack is not active.

## Layout
- `agent.manifest.yaml` — the signed contract the gateway enforces
- `prompts/system.md` — pinned system prompt
- `evals/suite.md` — eval suite stub
- `runbook.md` — day-2 operations
"""


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Scaffold a new Aegis agent.")
    parser.add_argument("--id", required=True, help="agent id (kebab-case)")
    parser.add_argument("--owner", required=True, help="owning department (e.g. dept-it)")
    parser.add_argument(
        "--pack", required=True, choices=sorted(_PACK_DEFAULTS), help="compliance pack"
    )
    parser.add_argument(
        "--blast-radius", default="low", choices=["low", "medium", "high"]
    )
    parser.add_argument(
        "--out-dir",
        default=os.path.join(_REPO_ROOT, "sample_agents"),
        help="base directory for the generated agent package",
    )
    args = parser.parse_args(argv)

    defaults = _PACK_DEFAULTS[args.pack]
    manifest_text = _manifest_yaml(args, defaults)

    # Validate BEFORE writing anything.
    parsed = manifest_loader.parse_yaml(manifest_text)
    errs = manifest_loader.validate_manifest(parsed)
    if errs:
        print("ERROR: generated manifest is not conformant:", file=sys.stderr)
        for e in errs:
            print(f"  - {e}", file=sys.stderr)
        return 2

    agent_dir = os.path.join(args.out_dir, args.id)
    os.makedirs(os.path.join(agent_dir, "prompts"), exist_ok=True)
    os.makedirs(os.path.join(agent_dir, "evals"), exist_ok=True)

    files = {
        os.path.join(agent_dir, "agent.manifest.yaml"): manifest_text,
        os.path.join(agent_dir, "prompts", "system.md"): _system_prompt(args),
        os.path.join(agent_dir, "evals", "suite.md"): _evals(args),
        os.path.join(agent_dir, "runbook.md"): _runbook(args),
        os.path.join(agent_dir, "README.md"): _readme(args, defaults),
    }
    for path, content in files.items():
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)

    print(f"OK: scaffolded conformant agent '{args.id}' at {agent_dir}")
    print(f"    pack={args.pack} owner={args.owner} blast_radius={args.blast_radius}")
    print("    files:")
    for path in files:
        print(f"      - {os.path.relpath(path, _REPO_ROOT)}")
    print("    manifest validated against agent-manifest.schema.json: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
